EVALUATE
ADDCOLUMNS(
  sales,
  "sale_price", sales[sale_quantity] * sales[price],
  "days_before_migration", DATEDIFF(RELATED(dates[date]), Date(2025, 02, 14),DAY)
  )
  ORDER BY
  [days_before_migration] DESC
