table customers
	lineageTag: 0402139a-9ab9-4264-85ee-387796dd943d

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: 7eaeead9-3523-43d2-932a-e125ef807649
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_name
		dataType: string
		lineageTag: 2ac9beb5-5d34-4881-98eb-3dc5e8bdc5f3
		summarizeBy: none
		sourceColumn: customer_name

		annotation SummarizationSetBy = Automatic

	column customer_payment_type
		dataType: string
		lineageTag: d7bf2dd1-a81c-493f-b706-81482ce32e47
		summarizeBy: none
		sourceColumn: customer_payment_type

		annotation SummarizationSetBy = Automatic

	column customer_age
		dataType: int64
		formatString: 0
		lineageTag: 42d04952-e4fb-4a10-851c-f600bc96e1fa
		summarizeBy: sum
		sourceColumn: customer_age

		annotation SummarizationSetBy = Automatic

	column customer_region
		dataType: string
		lineageTag: 1bf8a2ac-9a7d-4566-93ed-b61f6b5cc1b3
		summarizeBy: none
		sourceColumn: customer_region

		annotation SummarizationSetBy = Automatic

	column customer_signup_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: e7263806-511d-4843-97aa-52b49e300b4f
		summarizeBy: none
		sourceColumn: customer_signup_date

		variation Variation
			isDefault
			relationship: 1c4fddf1-2130-4aad-9b65-5842da94b5c3
			defaultHierarchy: LocalDateTable_fdb14f2e-7fca-43c7-93b5-c164e9717cb4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition customers = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\nistl\OneDrive\Documents\dataviz-project\customers.csv"),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", Int64.Type}, {"customer_name", type text}, {"customer_payment_type", type text}, {"customer_age", Int64.Type}, {"customer_region", type text}, {"customer_signup_date", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

