table dates
	lineageTag: c50d19fa-4583-40b6-abdc-f387116ff7bf

	column date_id
		dataType: int64
		formatString: 0
		lineageTag: 7ed39517-40ca-45ea-8a6f-1e0c1873f8e5
		summarizeBy: none
		sourceColumn: date_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3fbf857b-ad50-4cc0-8439-34159ce716de
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: 87488ff7-7774-4855-9108-42c48951a70a
			defaultHierarchy: LocalDateTable_2838584e-c11a-4f0d-a4b5-096369b7e236.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column date_month
		dataType: int64
		formatString: 0
		lineageTag: 41fd3ef9-bcb9-40dd-960d-74d205604be4
		summarizeBy: sum
		sourceColumn: date_month

		annotation SummarizationSetBy = Automatic

	column date_day
		dataType: int64
		formatString: 0
		lineageTag: 06210d53-5478-4897-a075-be0b58c3ce49
		summarizeBy: sum
		sourceColumn: date_day

		annotation SummarizationSetBy = Automatic

	column date_weekday
		dataType: string
		lineageTag: aa9e9b4c-b29d-495d-aed3-4cd81fa230ee
		summarizeBy: none
		sourceColumn: date_weekday

		annotation SummarizationSetBy = Automatic

	column date_week
		dataType: int64
		formatString: 0
		lineageTag: bf54ef0b-eafc-4d3d-b647-ff50d9e7c5ff
		summarizeBy: sum
		sourceColumn: date_week

		annotation SummarizationSetBy = Automatic

	partition dates = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Library DIN\Documents\GitHub\dataviz-powerbi\dates.csv"),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"date_id", Int64.Type}, {"date", type date}, {"date_month", Int64.Type}, {"date_day", Int64.Type}, {"date_weekday", type text}, {"date_week", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

