table products
	lineageTag: d84e2ece-d7fe-4c8d-b63f-506733584099

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: 5f439984-f65c-46fe-ba97-94906b08a432
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		lineageTag: a3c66cbf-0e6f-4fef-a002-27ff54be57d9
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

	column product_category
		dataType: string
		lineageTag: ebe5a197-eee3-46c2-8031-b729a0fb44cc
		summarizeBy: none
		sourceColumn: product_category

		annotation SummarizationSetBy = Automatic

	column product_brand
		dataType: string
		lineageTag: 7c3ac6eb-597c-4688-b2b1-05e77df65049
		summarizeBy: none
		sourceColumn: product_brand

		annotation SummarizationSetBy = Automatic

	column product_model
		dataType: string
		lineageTag: bda3d4d8-a0bb-434a-8459-7b127342845f
		summarizeBy: none
		sourceColumn: product_model

		annotation SummarizationSetBy = Automatic

	column product_list_price
		dataType: double
		lineageTag: 59408aa3-464d-4188-8b45-f8ce3cc4f236
		summarizeBy: none
		sourceColumn: product_list_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column product_standard_cost
		dataType: double
		lineageTag: 92fd31a2-2169-4e83-b391-3380940f25da
		summarizeBy: none
		sourceColumn: product_standard_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column product_is_active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b02a9541-0959-4eb3-a603-a472b3cf8f29
		summarizeBy: none
		sourceColumn: product_is_active

		annotation SummarizationSetBy = Automatic

	partition products = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Library DIN\Documents\GitHub\dataviz-powerbi\products.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"product_id", Int64.Type}, {"product_name", type text}, {"product_category", type text}, {"product_brand", type text}, {"product_model", type text}, {"product_list_price", type number}, {"product_standard_cost", type number}, {"product_is_active", type logical}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

