table stores
	lineageTag: f4a2efb8-e74a-47c8-a3a3-e3524a63f9db

	measure oldest_store_open_date = MIN(stores[store_open_date])
		formatString: General Date
		lineageTag: aa0b487e-b6b9-42cb-b622-78b30cab256d

	column store_id
		dataType: int64
		formatString: 0
		lineageTag: be1523f4-0f9c-4a5b-b6f3-c70ccef80c7f
		summarizeBy: none
		sourceColumn: store_id

		annotation SummarizationSetBy = Automatic

	column store_name
		dataType: string
		lineageTag: e0c2d218-b89a-448c-9af0-cb672f831a22
		summarizeBy: none
		sourceColumn: store_name

		annotation SummarizationSetBy = Automatic

	column store_type
		dataType: string
		lineageTag: 55c0f39a-0e05-495d-bd4e-a273d7913acf
		summarizeBy: none
		sourceColumn: store_type

		annotation SummarizationSetBy = Automatic

	column store_open_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5b7420ed-155e-4b39-952a-37d32edcdac9
		summarizeBy: none
		sourceColumn: store_open_date

		variation Variation
			isDefault
			relationship: 86949a54-8f9e-4569-8bb3-7aa4857846ee
			defaultHierarchy: LocalDateTable_22d5fd13-26e2-4a4c-8784-518589dc9bb1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column store_location
		dataType: string
		lineageTag: 66722ec2-cabc-4155-a983-aa9ff57f183a
		summarizeBy: none
		sourceColumn: store_location

		annotation SummarizationSetBy = Automatic

	partition stores = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Library DIN\Documents\GitHub\dataviz-powerbi\stores.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"store_id", Int64.Type}, {"store_name", type text}, {"store_type", type text}, {"store_open_date", type date}, {"store_location", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

